# 全局设置
[global]
https = true # 使用HTTPS协议
process = 4 # 进程数
log = "bilibili.log" # 日志文件名

# 代理设置
[proxy]
enable = true # 开关
pool = "proxy.txt" # 代理池，这个不用管，实际并没有用到

# 用户设置
[user]
update = true # 自动更新凭据
force_refresh_token = true # 强制刷新Token
account = """
username=我怎么知道;password=我怎么知道;
"""
# 请在上方填写您的账号凭据, 每一条凭据应至少包含下述三种身份校验方式之一的完整键值对:
# Password: username=...;password=...;
# Token: access_token=...;refresh_token=...;
# Cookie: bili_jct=...;DedeUserID=...;DedeUserID__ckMd5=...;sid=...;SESSDATA=...;

[live]
room_info = [
    ['2603963','0','0','28800','0','213000','020000'],
    ['53849','1','0','28800','0','220000','040000']
]
# 在上方填写每个房间的信息，每个房间是一个list，格式为[房间号，是否需要录制，是否需要黑色遮挡，最大录制时间，是否上传,录制开始时间,录制结束时间]
# 请尽量关闭黑色遮挡，减小CPU压力
# 录制开始时间和结束时间可以同时设置为'0'，表示一直允许录制

[output]
path = 'rec'

[log]
# 静态参数，可以设置为'NOTSET', 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
level = 'INFO'

[paras]
# 请自己估算给一个4小时的视频添加黑色遮挡的转码时间，默认1小时
expire = 3600